StringIndex
typedef str_t::value_type StringIndex< str_t >::char_t
The character type contained in the str_t.
std::vector<str_t> StringIndex< str_t >::longLib
The library for all words that have a length >= gramSize * 2.
std::vector<str_t> StringIndex< str_t >::shortLib
The library for all words that have a length < gramSize * 2.
std::unordered_map<str_t*, std::vector<std::pair<str_t, float> > > StringIndex< str_t >::wordMap
All words, mapped to their master keys. A search result will always be redirected to its master keys.
std::unordered_map<str_t, std::unordered_set<str_t*> > StringIndex< str_t >::ngrams
The n-gram library generated.
int16_t StringIndex< str_t >::gramSize
the size of n-grams
size_t StringIndex< str_t >::sectionSize
The section size of strings for each getMatchScore loop block.
std::atomic<bool> StringIndex< str_t >::indexed
Indicator of whether the library has been indexed. If not indexed, no search can be done.
const float StringIndex< str_t >::distanceFactor
deprecated
StringIndex< str_t >::StringIndex(char_t **const words, const size_t size, const uint16_t rowSize, float *const weight, const uint16_t gSize)
Constructs the StringIndex class by indexing the strings based on an array of words words Words to be searched for. For each row, the first word is used as the master key, in which the row size is rowSize. All rows are flattened into a 1D-array, and can be extracted based on rowSize. In a search, all queries of the words in a row will return the master key. size size of the words rowSize size of each text rows of words. weight A list of weight values for each key. It should be at least as long as the number of rows, i.e. size / rowSize. gSize size of grams to be created. Default 3.
StringIndex< str_t >::StringIndex(char_t ***const words, const size_t size, const uint16_t rowSize, float **const weight, const uint16_t gSize)
Constructs the StringIndex class by indexing the strings based on an array of words words Words to be searched for. For each row, the first word is used as the master key, in which the row size is rowSize. Each row is in a separate sub-array. In a search, all queries of the words in a row will return the master key. size size of the words rowSize size of each text rows of words. weight A list of weight values for each key. It should be at least as long as the number of rows, i.e. size / rowSize. gSize size of grams to be created. Default 3.
StringIndex< str_t >::StringIndex(std::vector< std::vector< str_t >> &words, const int16_t gSize, std::vector< std::vector< float >> &weight)
Constructs the StringIndex class by indexing the strings based on an array of words words Words to be searched for. For each row, the first word is used as the master key, in which the row size is rowSize. Each row is in a separate sub-array. In a search, all queries of the words in a row will return the master key. size size of the words rowSize size of each text rows of words. weight A list of weight values for each key. It should be at least as long as the number of rows, i.e. size / rowSize. gSize size of grams to be created. Default 3.
void StringIndex< str_t >::init(std::unordered_map< str_t, std::vector< std::pair< str_t, float >>> &tempWordMap)
Initiates the word map by assigning the same strings to a pointer, to save space. tempWordMap A temprary word map of strings. Key: query terms. Value: a list of master keys and corresponding scores that the queries point to.
void StringIndex< str_t >::getGrams(str_t *str)
Generate n-grams from a string based on the member variable gramSize. str A pointer to the string to generate n-grams from.
void StringIndex< str_t >::getGrams(const str_t &str, std::vector< str_t > &generatedGrams)
Generate n-grams from a string based on the member variable gramSize, and store in an array. str A pointer to the string to generate n-grams from. generatedGrams A vector to store the genearated n-grams
void StringIndex< str_t >::buildGrams()
Build n-grams for the member variable longLib
References indexed.
size_t StringIndex< str_t >::stringMatch(const str_t &query, const str_t &source, std::vector< size_t > &row1, std::vector< size_t > &row2)
Computes the percentage of query matches source. query A query string source A source string in the library to compare to. row1 A temporary vector as a cache for the algorithm. Its size must at least (the max size of query and source) + 1. row2 A temporary vector as a cache for the algorithm. Its size must at least (the max size of query and source) + 1.
void StringIndex< str_t >::getMatchScore(const str_t &query, size_t first, std::vector< str_t *> &targets, std::vector< float > &currentScore)
A looper to calculate match scores query The query string. first The starting index to loop from. targets The target strings that have been scored currentScore The score for each strings in targets
Referenced by StringIndex< str_t >::searchShort.
void StringIndex< str_t >::searchShort(str_t &query, std::unordered_map< str_t *, float > &score)
Search in the shortLib query The query string. score Targets found paired with their corresponding cores generated.
References StringIndex< str_t >::getMatchScore.
Referenced by StringIndex< str_t >::_search.
void StringIndex< str_t >::searchLong(str_t &query, std::unordered_map< str_t *, float > &score)
Search in the longLib query The query string. score Targets found paired with their corresponding cores generated.
Referenced by StringIndex< str_t >::_search.
void StringIndex< str_t >::_search(const char_t *query, const float threshold, const uint32_t limit, std::vector< str_t > &result)
The worker function for search query The query string. threshold Lowest acceptable match ratio for a string to be included in the results. limit The maximum number of results to generate. result The matching strings to be selected, sorted from highest score to lowest.
References StringIndex< str_t >::searchShort, StringIndex< str_t >::searchLong.
void StringIndex< str_t >::search(const char_t *query, char_t ***results, uint32_t *size, const float threshold, uint32_t limit)
The search interface function, calls _search query The query string. results The matching strings to be selected, sorted from highest score to lowest. size The number of strings in the result array. threshold Lowest acceptable match ratio for a string to be included in the results. limit The maximum number of results to generate.
References indexed.
void StringIndex< str_t >::release(char_t ***results, size_t size) const
Release a result pointer that have been generated in search results The matching strings to be selected, allocated using the new operator.
uint64_t StringIndex< str_t >::size()
Get the size of the word map wordMap
uint64_t StringIndex< str_t >::libSize()
Get the size of the n-gram library ngrams
static bool StringIndex< str_t >::compareScores(std::pair< str_t, float > &a, std::pair< str_t, float > &b)
Compare pairs of string-score by their score, and length. Greater scores and shorter lengths will be prioritized a The first pair of string-score b The second pair of string-score
static void StringIndex< str_t >::trim(str_t &s)
Trim a string from both ends (in place) s The string to be trimmed